[0m14:47:55.078444 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10594e140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108672ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108670e80>]}


============================== 14:47:55.081312 | fd48951d-c18d-4a3b-976b-d4b80cf333a5 ==============================
[0m14:47:55.081312 [info ] [MainThread]: Running with dbt=1.7.4
[0m14:47:55.081603 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/himishatunwal/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt seed', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:47:55.081912 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/himishatunwal/Develop/DBT_CAPSTONE_PROJECT/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:47:55.083446 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_wall_clock_time": 0.0320975, "process_user_time": 0.884167, "process_kernel_time": 0.092079, "process_mem_max_rss": "108544000", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:47:55.083807 [debug] [MainThread]: Command `dbt seed` failed at 14:47:55.083737 after 0.03 seconds
[0m14:47:55.083999 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10594e140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086e73a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086e4880>]}
[0m14:47:55.084182 [debug] [MainThread]: Flushing usage events
[0m14:47:55.191405 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
